# Generated by Django 3.1.3 on 2020-11-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201127_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuee',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting for Rescuers'), ('Going', 'Rescuers on the Way')], default='Going', max_length=30),
        ),
    ]
