# Generated by Django 3.1.1 on 2020-11-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201127_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuee',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting', 'Waiting for Rescuers'), ('Going', 'Rescuers on the Way')], default='Going', max_length=30),
        ),
    ]
