# Generated by Django 3.1.1 on 2020-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201127_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuee',
            name='children',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rescuee',
            name='disaster',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rescuee',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rescuee',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rescuee',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rescuee',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
