# Generated by Django 3.1.1 on 2020-11-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201128_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuee',
            name='senior',
            field=models.IntegerField(blank=True),
        ),
    ]
